ARG UBUNTU_VER=jammy
ARG MACHINARIS_STREAM=main

FROM ghcr.io/guydavis/machinaris-base-${UBUNTU_VER}:${MACHINARIS_STREAM}

ARG DEBIAN_FRONTEND=noninteractive
ARG CHIADOG_BRANCH=main
ARG FDCLI_BRANCH=master
ARG BLADEBIT_BRANCH=master

ARG APPLE_BRANCH
ARG BPX_BRANCH
ARG BTCGREEN_BRANCH
ARG CACTUS_BRANCH
ARG CHIA_BRANCH
ARG CHINILLA_BRANCH
ARG CHIVES_BRANCH
ARG CRYPTODOGE_BRANCH
ARG ECOSTAKE_BRANCH
ARG FLAX_BRANCH
ARG FLORA_BRANCH
ARG GOLD_BRANCH
ARG HDDCOIN_BRANCH
ARG LITTLELAMBOCOIN_BRANCH
ARG MAIZE_BRANCH
ARG MINT_BRANCH
ARG MMX_BRANCH
ARG NCHAIN_BRANCH
ARG PETROLEUM_BRANCH
ARG PROFIT_BRANCH
ARG SHIBGREEN_BRANCH
ARG SILICOIN_BRANCH
ARG STAICOIN_BRANCH
ARG STOR_BRANCH
ARG TAD_BRANCH
ARG WHEAT_BRANCH

# copy local files
COPY . /machinaris/

# set workdir
WORKDIR /chia-blockchain

# Install specific blockchain fork (based on branch enabled) + tools that depend on the fork
RUN \
	/usr/bin/bash /machinaris/scripts/forks/apple_install.sh ${APPLE_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/bpx_install.sh ${BPX_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/btcgreen_install.sh ${BTCGREEN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/cactus_install.sh ${CACTUS_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/chia_install.sh ${CHIA_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/chives_install.sh ${CHIVES_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/chinilla_install.sh ${CHINILLA_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/cryptodoge_install.sh ${CRYPTODOGE_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/ecostake_install.sh ${ECOSTAKE_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/flax_install.sh ${FLAX_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/flora_install.sh ${FLORA_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/gold_install.sh ${GOLD_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/hddcoin_install.sh ${HDDCOIN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/littlelambocoin_install.sh ${LITTLELAMBOCOIN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/maize_install.sh ${MAIZE_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/mint_install.sh ${MINT_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/mmx_install.sh ${MMX_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/nchain_install.sh ${NCHAIN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/petroleum_install.sh ${PETROLEUM_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/profit_install.sh ${PROFIT_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/shibgreen_install.sh ${SHIBGREEN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/silicoin_install.sh ${SILICOIN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/staicoin_install.sh ${STAICOIN_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/stor_install.sh ${STOR_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/tad_install.sh ${TAD_BRANCH} \
	&& /usr/bin/bash /machinaris/scripts/forks/wheat_install.sh ${WHEAT_BRANCH} \
    && /usr/bin/bash /machinaris/scripts/pull_3rd_party_libs.sh \
	&& /usr/bin/bash /machinaris/scripts/machinaris_install.sh \
	&& /usr/bin/bash /machinaris/scripts/i18n/compile.sh \
	&& rm -rf \
		/root/.cache \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*

# Provide a colon-separated list of in-container paths to your mnemonic keys
ENV keys="/root/.chia/mnemonic.txt"  
# Provide a colon-separated list of in-container paths to your completed plots
ENV plots_dir="/plots"
# One of fullnode, farmer, harvester, plotter, farmer+plotter, harvester+plotter. Default is fullnode
ENV mode="fullnode" 
# The single blockchain to run: chia, flax, nchain, hddcoin, chives, etc
ENV blockchains="chia"
# If provided then these optional 3 public keys will be set in your plotman.yaml
ENV farmer_pk="null"
ENV pool_pk="null"
ENV pool_contract_address="null"
# If mode=harvester, required for host and port the harvester will your farmer
ENV farmer_address="null"
ENV farmer_port="8447"
# Can override the location of default settings for api and web servers.
ENV API_SETTINGS_FILE='/root/.chia/machinaris/config/api.cfg'
ENV WEB_SETTINGS_FILE='/root/.chia/machinaris/config/web.cfg'
# Local network hostname of a Machinaris controller - localhost when standalone
ENV controller_host="localhost"
ENV controller_web_port=8926
ENV controller_api_port=8927
ENV worker_address="null"
ENV worker_api_port=8927
# Some placeholders for Nvidia GPU support in MMX
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Set env vars requried by forktools
ENV FORKTOOLSDIR=/forktools
ENV FORKTOOLSBLOCKCHAINDIRS=/
ENV FORKTOOLSHIDDENDIRS=/root

ENV PATH="${PATH}:/chia-blockchain/venv/bin:/forktools:/mmx-node/build"
ENV TZ=Etc/UTC
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV FLASK_ENV=production
ENV XDG_CONFIG_HOME=/root/.chia
ENV AUTO_PLOT=false
ENV CHIADOG_BRANCH=${CHIADOG_BRANCH}
ENV FDCLI_BRANCH=${FDCLI_BRANCH}
ENV BLADEBIT_BRANCH=${BLADEBIT_BRANCH}

VOLUME [ "/id_rsa" ]

# Chia protocol port - forward at router
EXPOSE 8444
# Chia farmer port - DO NOT forward at router
EXPOSE 8447
# Machinaris WebUI - DO NOT forward at router, proxy if needed
EXPOSE 8926
# Machinaris API - DO NOT forward at router
EXPOSE 8927

WORKDIR /chia-blockchain
ENTRYPOINT ["bash", "./entrypoint.sh"]
