ARG MACHINARIS_STREAM=test

FROM ghcr.io/guydavis/machinaris-base:${MACHINARIS_STREAM}

ARG DEBIAN_FRONTEND=noninteractive
ARG CHIA_FORK=chia
ARG FORK_REPO_URL=https://github.com/Chia-Network/chia-blockchain.git
ARG FORK_BRANCH=1.2.11
ARG FORK_CHIADOG_PREFIX=chia

# Symbol of the Fork
ARG CHIA_FORK_SYMBOL=xch
# Command used by fork e.g. chia/sit/...
ARG FORK_CMD=${CHIA_FORK}
# Download URL for blockchain DB
ARG FORK_DOWNLOAD_URL=""
# Name of config directory in /root/.${CONFIG_DIR} e.g. "ext9" for nchain
ARG FORK_CONFIG_DIR=/root/.${CHIA_FORK}
# Install directory e.g. "chia" == /chia-blockchain
ARG FORK_INSTALL_DIR=/${CHIA_FORK}-blockchain


# copy local files
COPY . /machinaris/

RUN \
  /usr/bin/bash /machinaris/scripts/fork_install.sh \
  && /usr/bin/bash /machinaris/scripts/machinaris_install.sh \
  && apt-get clean \
  && rm -rf \
    /root/.cache \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

# Export ARGs to Env
ENV CHIA_FORK_SYMBOL=${CHIA_FORK_SYMBOL}
ENV FORK_CMD=${FORK_CMD}
ENV FORK_DOWNLOAD_URL=${FORK_DOWNLOAD_URL}
ENV FORK_CONFIG_DIR=${FORK_CONFIG_DIR}
ENV FORK_INSTALL_DIR=${FORK_INSTALL_DIR}
ENV FORK_CHIADOG_PREFIX=${FORK_CHIADOG_PREFIX}

# Provide a colon-separated list of in-container paths to your mnemonic keys
ENV keys="/root/.chia/mnemonic.txt"  
# Provide a colon-separated list of in-container paths to your completed plots
ENV plots_dir="/plots"
# One of fullnode, farmer, harvester, plotter, farmer+plotter, harvester+plotter. Default is fullnode
ENV mode="fullnode" 
# The single blockchain to run: chia, flax, nchain, hddcoin, chives, etc
ENV blockchains="${CHIA_FORK}"
# If provided then these optional 3 public keys will be set in your plotman.yaml
ENV farmer_pk="null"
ENV pool_pk="null"
ENV pool_contract_address="null"
# If mode=harvester, required for host and port the harvester will your farmer
ENV farmer_address="null"
ENV farmer_port="8447"
# Can override the location of default settings for api and web servers.
ENV API_SETTINGS_FILE='/root/.chia/machinaris/config/api.cfg'
ENV WEB_SETTINGS_FILE='/root/.chia/machinaris/config/web.cfg'
# Local network hostname of a Machinaris controller - localhost when standalone
ENV controller_host="localhost"
ENV controller_web_port=8926
ENV controller_api_port=8927
ENV worker_address="null"
ENV worker_api_port=8927
# Some placeholders for Nvidia GPU support in MMX
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Set env vars requried by forktools
ENV FORKTOOLSDIR=/forktools
ENV FORKTOOLSBLOCKCHAINDIRS=/
ENV FORKTOOLSHIDDENDIRS=/root

ENV PATH="${PATH}:/chia-blockchain/venv/bin:/forktools:/mmx-node/build"
ENV TZ=Etc/UTC
ENV FLASK_ENV=production
ENV XDG_CONFIG_HOME=/root/.chia
ENV AUTO_PLOT=false

VOLUME [ "/id_rsa" ]

# Chia protocol port - forward at router
EXPOSE 8444
# Chia farmer port - DO NOT forward at router
EXPOSE 8447
# Machinaris WebUI - DO NOT forward at router, proxy if needed
EXPOSE 8926
# Machinaris API - DO NOT forward at router
EXPOSE 8927

WORKDIR /chia-blockchain
CMD ["bash", "/machinaris/docker/entrypoint.sh"]
