"""empty message

Revision ID: 013b8bed94b0
Revises: 241cf86f57bd
Create Date: 2021-10-24 19:51:15.674304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013b8bed94b0'
down_revision = '241cf86f57bd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_plot_count', sa.Column('blockchain', sa.String(length=64), nullable=True))
    op.add_column('stat_plots_size', sa.Column('blockchain', sa.String(length=64), nullable=True))
    op.add_column('stat_plots_total_used', sa.Column('blockchain', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_plots_total_used', 'blockchain')
    op.drop_column('stat_plots_size', 'blockchain')
    op.drop_column('stat_plot_count', 'blockchain')
    # ### end Alembic commands ###

