"""empty message

Revision ID: 06123bbe2d59
Revises: 7a66cdc8385a
Create Date: 2021-11-17 14:31:05.999542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06123bbe2d59'
down_revision = '7a66cdc8385a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('cold_balance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'cold_balance')
    # ### end Alembic commands ###


def upgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

