"""empty message

Revision ID: 292c8d1a45fb
Revises: bb1f1d3ee5d0
Create Date: 2021-10-06 10:07:51.279047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292c8d1a45fb'
down_revision = 'bb1f1d3ee5d0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plottings', sa.Column('blockchain', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plottings', 'blockchain')
    # ### end Alembic commands ###


def upgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

