"""empty message

Revision ID: d3405f8485d9
Revises: fc3cc23ea246
Create Date: 2021-09-16 09:15:19.178262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3405f8485d9'
down_revision = 'fc3cc23ea246'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farms')
    op.create_table('farms',
        sa.Column('hostname', sa.String(length=255), nullable=False),
        sa.Column('blockchain', sa.String(length=64), nullable=False),
        sa.Column('mode', sa.String(length=32), nullable=False),
        sa.Column('status', sa.String(length=128), nullable=False),
        sa.Column('plot_count', sa.REAL(), nullable=False),
        sa.Column('plots_size', sa.REAL(), nullable=False),
        sa.Column('total_coins', sa.REAL(), nullable=False),
        sa.Column('netspace_size', sa.REAL(), nullable=False),
        sa.Column('expected_time_to_win', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('hostname', 'blockchain')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farms')
    op.create_table('farms',
        sa.Column('hostname', sa.String(length=255), nullable=False),
        sa.Column('mode', sa.String(length=32), nullable=False),
        sa.Column('status', sa.String(length=128), nullable=False),
        sa.Column('plot_count', sa.REAL(), nullable=False),
        sa.Column('plots_size', sa.REAL(), nullable=False),
        sa.Column('total_chia', sa.REAL(), nullable=False),
        sa.Column('netspace_size', sa.REAL(), nullable=False),
        sa.Column('expected_time_to_win', sa.String(length=64), nullable=False),
        sa.Column('total_flax', sa.REAL(), nullable=False),
        sa.Column('flax_netspace_size', sa.REAL(), nullable=False),
        sa.Column('flax_expected_time_to_win', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('hostname', 'blockchain')
    )
    # ### end Alembic commands ###


def upgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_stats():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

