name: develop-flax

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: docker/dockerfile
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            "MACHINARIS_STREAM=develop"
            "FLAX_BRANCH=main"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/machinaris-flax:develop
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/machinaris-flax:develop
