name: release-one

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version' 

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: docker/dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            "UBUNTU_VER=jammy"
            "MACHINARIS_STREAM=latest"
            "ONE_BRANCH=main"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/machinaris-one:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/machinaris-one:v${{ github.event.inputs.version }}
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/machinaris-one:latest
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/machinaris-one:v${{ github.event.inputs.version }}
